Remove duplicate integration resource ID on fetch
fetch() expects a type endpoint.  It appends the resource ID itself.

Also fixes a rather confusing:

> TypeError: fetch() takes at least 2 arguments (2 given)